{{- if or .Values.networkPolicy.ingress .Values.networkPolicy.egress }}
{{- $networkPolicyName :=  include "launch-darkly.fullname" . | lower }}
{{- if eq .Values.networkPolicy.flavour "cilium" }}
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: {{ $networkPolicyName }}
  labels:
    {{- include "launch-darkly.labels" . | nindent 4 }}
spec:
  endpointSelector:
    matchLabels:
      {{- include "launch-darkly.selectorLabels" . | nindent 6 }}
  {{- if .Values.networkPolicy.ingress }}
  ingress:
    {{- .Values.networkPolicy.ingress | toYaml | nindent 4 }}
  {{- end}}
  {{- if .Values.networkPolicy.egress }}
  egress:
    {{- .Values.networkPolicy.egress | toYaml | nindent 4 }}
  {{- end}}
{{- else }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ $networkPolicyName}}
  labels:
    {{- include "launch-darkly.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "launch-darkly.selectorLabels" . | nindent 6 }}
  {{- if .Values.networkPolicy.ingress }}
  ingress:
    {{- .Values.networkPolicy.ingress | toYaml | nindent 4 }}
  {{- end}}
  {{- if .Values.networkPolicy.egress }}
  egress:
    {{- .Values.networkPolicy.egress | toYaml | nindent 4 }}
  {{- end}}
  policyTypes:
    {{- if .Values.networkPolicy.ingress }}
    - Ingress
    {{- end}}
    {{- if .Values.networkPolicy.egress }}
    - Egress
    {{- end}}
{{- end }}
{{- end }}
