apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "launch-darkly.fullname" . }}
  labels:
    {{- include "launch-darkly.labels" . | nindent 4 }}
spec:
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  selector:
    matchLabels:
      {{- include "launch-darkly.selectorLabels" . | nindent 6 }}
